### ISSUE TITLE
Tectonic fails with "DVI stack depth is not zero at end of page"

### ISSUE THREAD

**Issue by mirandadam** [tectonic-typesetting/tectonic#106]
Tectonic fails with "DVI stack depth is not zero at end of page" when trying to render a minimal example using package fourier.

I know there are plenty of ways to render a º symbol in latex, but this is a minimal example to show that somehow tectonic is incompatible with the fourier package. At the moment it seems to me a it's a bug in tectonic (or maybe XeTeX), since my installation is TexLive (vanilla install-tl) and it works. Since tectonic is also based on TexLive, even if it's a bug on XeTeX it might be sidestepped just by using TexLive instead. Please take a look into this.

By the way, thanks for the awesome package! It should make the LaTex workflow much simpler for me. I read about it this-week-in-rust.org number 184.

The full message is:

> $ tectonic a.tex
> Running TeX ...
> Rerunning TeX because "a.aux" changed ...
> Running xdvipdfmx ...
> error: DVI stack depth is not zero at end of page

pdflatex works:

> $ pdflatex a.tex
> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
> restricted \write18 enabled.
> entering extended mode
> (./a.tex
> [... lots of stuff here ...]
> Output written on a.pdf (1 page, 18325 bytes).
> Transcript written on a.log.

If I suppress `\usepackage{fourier}` from the .tex file, tectonic finishes with no warnings but does not render the `\degree` (°) symbols. Without `\usepackage{fourier}`, pdflatex fails:
> $ pdflatex a.tex
>...
>! Package inputenc Error: Unicode char ° (U+B0)
>(inputenc)                not set up for use with LaTeX.
>...

This is the minimal example I used (renamed to a.tex.txt to make github happy):
[a.tex.txt](https://github.com/tectonic-typesetting/tectonic/files/1082565/a.tex.txt)

My environment:
> $ tectonic -V
>Tectonic 0.1.5
> $ uname -a
>Linux c 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> $ pdflatex -v
>pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
>kpathsea version 6.2.3
>Copyright 2017 Han The Thanh (pdfTeX) et al.
>There is NO warranty.  Redistribution of this software is
>covered by the terms of both the pdfTeX copyright and
>the Lesser GNU General Public License.
>For more information about these matters, see the file
>named COPYING and the pdfTeX source.
>Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
>Compiled with libpng 1.6.29; using libpng 1.6.29
>Compiled with zlib 1.2.11; using zlib 1.2.11
>Compiled with xpdf version 3.04
> $ cargo install-update -a
>    Updating registry `https://github.com/rust-lang/crates.io-index`
>
>Package       Installed  Latest    Needs update
>cargo-update  v1.1.1     v1.1.1    No
>clippy        v0.0.140   v0.0.140  No
>rustfmt       v0.9.0     v0.9.0    No
>tectonic      v0.1.5     v0.1.5    No
>racer         v2.0.8     v2.0.8    No
>
>No packages need updating.
> $ cargo -V
>cargo 0.20.0-nightly (bbfe9b3a9 2017-06-05)

**Comment by rekka** [comment]
Thanks for the detailed report!

I can confirm the error with the latest development version of tectonic (on macOS). Both

```
pdflatex a.tex
xelatex a.tex
```

produce a pdf output without errors, however xelatex inserts 'ř' instead of '°'. So there are some incompatibilities between pdflatex and xelatex to begin with.

Since the `fourier` package enables Utopia fonts, it might be a font handling issue in `xdvipdfmx`. It might be fixed by #61.

**Comment by pkgw** [comment]
Yes, thanks. Here's the simplest test case I can devise:

```
\documentclass{article}
\usepackage{fourier}
\begin{document}
Degree: °.
\end{document}
```

If the `fourier` package is not included, I don't get an error, but the degree symbol doesn't show up at all.

**Comment by mirandadam** [comment]
Thanks for the fast answers, @rekka and @pkgw!!!

@pkgw just taught me what "minimal" means... ;-)

By the way, I tried
`tlmgr install xetex`
`xelatex a.tex`
and got the same results as @rekka (the 'ř' rendering). Oddly, in my full document, the '°' was rendered correctly outside of the `\begin{tabular}` block and as 'ř' inside the block when using XeTeX. Go figure. 

It seems the default font inside the tabular block when the fourier package is included has some issue with '°'.

This is what I have so far:
* The XeTeX included with tectonic 0.1.5 is broken.
* XeTeX and Fourier still have some issues. This is not related to tectonic.

I guess the first bullet should be fixed when #61 arrives on crates.io. Does that make sense?

Best,
Daniel

**Comment by rekka** [comment]
I can confirm this bug also with package `mathptmx`:

```latex
\documentclass{article}
\usepackage{mathptmx}
\begin{document}
$\emptyset$
\end{document}
```

Tectonic's output:

```
Running TeX ...
Running xdvipdfmx ...
error: DVI stack depth is not zero at end of page
```

Package `mathptmx` loads the Adobe Times Ro­man (or equivalent) font, so it is probably related to #61.

**Comment by pkgw** [comment]
Sadly, updating to the very latest XeTeX (cf. #61) has not fixed this bug.

**Comment by pkgw** [comment]
It took a while to identify the problem, but I think PR #163 will fix this!
